version: '3'

services:
  frontend:
    hostname: localhost
    container_name: frontend
    build: ./dwi-frontend
    ports:
      - 80:80
  
  backend:
    container_name: backend
    build: ./dwi-backend
    ports:
      - 5000:80
